language: java
jdk:
    - oraclejdk8

node_js:
  - stable

before_install:
- npm install -g npm@latest
- npm install -g cordova ionic@latest
before_script:

script:
- npm install
- ionic platform add android
- ionic build android
after_success:

cache:
  directories:
    - "node_modules"
