language: java
jdk:
    - oraclejdk8

android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.1
  - android-23
  - extra-android-m2repository
  - extra-google-m2repository
  - sys-img-x86-android-23
  - extra

node_js:
  - stable

addons:
  sonarcloud:
    organization: "vvasiloud-github"
    token:
      secure: "o62XrKROtc6dbGZDO+gxR0mqCLDrgjlulu3LCxOANtv1DBjywjZVFk+oalwwzReXACwnFQ7qtZX64FPKMJfpumHCWAUAb0Menbj0e6d20c+n1/T/HeIqq00hFfQ0Z4I456yErjmHIsjfpCsqydBTibgA6AMMEZfJzfhMqJS3FmTdnT/Is6XASvQZF9aA9Di5mdsp8I53QWtedmKxVPEqkXuMpor3vORrzJU+23FXGTVYC07XK9mSy7L3HZc20BqPkeErAU4c08Ll5O+2yQWoka05h2kJsDIAbWsZJWthRKjQ8xizARxg8+BF6ddVkHkbkI664Z8HfsLVzdt3R6iaOHzjdYNnB0ZHTgEPMBdJevrRcLGPd61mijWtQFSrSduF1cE+IrVWb7wJtYzMJrd2cVPQGR+qHzvT6BZEB9SYFL1QrVoL2g0hlyDMvO4A9/hUPlpxZBdSQT0oCstciV5hi/PEAg4TF+3e8F6Hoban8Si8SAkqzgVDvafCVDw1O88+OP6jVKOuJNX157OVNmTioTz+B5bVKkS2kizjZEkyXMA4/mb4hnNg8s0qwaC/XODGG4Cbh4KctCUk1Hu+L5QM6Bcq6/BFjFNLGSuu3VV9mMxewjgEarDPV/lCB0tjVFWUu2IGqDkWlVRmfQTFwxjlOUgLlPnLnW7QIJhpVXt5e+M="

before_install:
  - npm install -g npm@latest
  - npm install -g cordova ionic@latest
before_script:
  - sonar-scanner

script:
  - npm install
  - ionic platform add android
  - ionic build android

after_success:

env:
  global:
    - ANDROID_TARGET=android-23
    - ANDROID_ABI=x86

cache:
  directories:
    - 'node_modules'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle/caches/'
    - '$HOME/.gradle/wrapper/'
    - '$HOME/.android/build-cache'
