sudo: required

language: java
jdk: oraclejdk8
  
services:
  - mongodb
  - docker

before_script:
  - env > .env
  
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 6f6008b6-9461-4949-b7fe-bfc92156919d

before_deploy:
  - cd $TRAVIS_BUILD_DIR && ls -la
  
deploy:
  provider: script
  script: chmod +x /scripts/docker.deploy.sh && /scripts/docker.deploy.sh
  skip_cleanup: true
  on:
    branch: master