language: java
sudo: required
install: true
addons:
  sonarcloud:
    organization: "vvasiloud-github"
    token:
      secure: "RS5xraEiwU/m5gQZMJxj6QZsHSw2f8Ms4ybAw9Lqcka1ecr9H4EWkwuF09ka07Qq4hR2JFF2ymNUAaRkyGK4NovcaWq8R90NkaXuJ/FFPdliP5wMwMQmPQ6Rb9asohTDVv/RAiCWO7J2G8RQjGtPSws2rFffMaJ6I9nMfgB7BaPtxCbh6veLlse9lyd8sbhwVeQxu9ogCzWgP3IsacPvS9G20bHls4/J2sB9VwbMl5lopVlsGWtzPeAHcqkce+1U3B3g6wg4apn+o7apIxq6o/L+WhoX/SJ/9xOIyvn6bv1Q6QSqHzxfM4qlsQ1UPVFxK7IdRXcWdA/umyVtvcmcgJm45M/fzSwNM8cZvG9PHCrXGKdfmva6JK6QJAT5s+l6PnL6g2NcinwvuPHA2ouzezQUcPphgj3Fp4vXs7M8gpQK6J7Ufbl4Lcmg5d3yXK8Zzt1FzeVNBeZzYZRl5b5Lx900Jzm0drKcYrly1KFEAaOdXkbcuApIM+TsfRPXr1a+HnoZrNEPTKnDuazJQ8kJJwAJ+Q+4yScfWeTYhlwHK09MLaJ61zNmsUIEBgvnzYv7X/oBNDCcZ3f7WHaCaJrbGE2MSgcb6Mn0yWZgYto985i36PKSUIrfJ/HgWSo6J52C2hdsePL8f5dedICTdwW+QSYgrh4ATzP/j4Y7o8gTm0c="
jdk:
  - oraclejdk8
services:
  - mongodb
  - docker
  - redis-server
  - rabbitmq

before_script:
  - env > .env
  
after_success:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  - bash <(curl -s https://codecov.io/bash) -t 6f6008b6-9461-4949-b7fe-bfc92156919d

before_deploy:
  - cd $TRAVIS_BUILD_DIR
  
deploy:
  provider: script
  script: chmod +x scripts/docker.build.sh && scripts/docker.build.sh
  skip_cleanup: true
  on:
    branch: master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'