version: '2'
services:
#
# Infrastructure Services
#
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
        - "5672:5672"
  elasticsearch:
    image: vvasiloud/vento-elasticsearch
    restart: always
    ports:
        - "9200:9200"
        - "9300:9300"  
  kibana:
    image: vvasiloud/vento-kibana
    restart: always
    ports:
        - "5601:5601"
  logstash:
    image: vvasiloud/vento-logstash
    restart: always
	
#
# Centralized Configuration
#
  config:
    image: vvasiloud/vento-config
    restart: always
    ports:
        - "8888:8888"
#
# Service Discovery - Eureka
#
  registry:
    image: vvasiloud/vento-registry
    restart: always
    ports:
        - "8761:8761"
#
# UAA Service
#	
  auth-service:
    image: vvasiloud/vento-auth
    restart: always
    ports:
        - "3000:3000"
#
# UAA Database Service
#
  auth-db:
    image: mongo:latest
    restart: always
    ports:
        - "3001:27017"
#
# Zuul Gateway / Ribbon load balancer
#	
  gateway:
    image: vvasiloud/vento-gateway
    restart: always
    ports:
        - "80:9000"
#
# Profile Service
#		
  profile-service:
    image: vvasiloud/vento-profile
    restart: always
    ports:
        - "1000:1000"
#
# Profile Database Service
#
  profile-db:
    image: mongo:latest
    restart: always
    ports:
        - "1001:27017"
#
# Match Service
#	
  match-service:
    image: vvasiloud/vento-match
    restart: always
    ports:
        - "2000:2000"
#
# Match Database Service
#
  match-db:
    image: mongo:latest
    restart: always
    ports:
        - "2001:27017" 
#
# Hystrix Monitoring
#		
  monitoring:
    image: vvasiloud/vento-monitoring
    restart: always
    ports:
        - "8989:8989" 
        - "8080:8080"

#
# Zipkin Tracing
#
  tracing:
    image: vvasiloud/vento-tracing
    restart: always
    ports:
        - "9411:9411"