version: '2'
services:
#
# Infrastructure Services
#
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672"
  elasticsearch:
    build:
      context: ./logging/elasticsearch/
      dockerfile: Dockerfile
    restart: always
    ports:
        - "9200:9200"
        - "9300:9300"  
  kibana:
    build:
      context: ./logging/kibana/
      dockerfile: Dockerfile
    restart: always
    ports:
        - "5601:5601"
  logstash:
    build:
      context: ./logging/logstash/
      dockerfile: Dockerfile
    restart: always

#
# Centralized Configuration
#
  config:
    build:
      context: ./config/
      dockerfile: Dockerfile
    restart: always
    ports:
        - "8888:8888"

#
# Service Discovery - Eureka
#
  registry:
    build:
      context: ./registry/
      dockerfile: Dockerfile
    restart: always
    ports:
        - "8761:8761"


#
# UAA Service
#
  auth-service:
    build:
      context: ./auth-service/
      dockerfile: Dockerfile
    restart: always
    ports:
        - "3000:3000"

#
# UAA Database Service
#
  auth-db:
    image: mongo:latest
    restart: always
    ports:
        - "3001:27017"

#
# Zuul Gateway / Ribbon load balancer
#
  gateway:
    build:
      context: ./gateway/
      dockerfile: Dockerfile
    restart: always
    ports:
        - "80:9000"

#
# Profile Service
#
  profile-service:
    build:
      context: ./profile-service/
      dockerfile: Dockerfile
    restart: always
    ports:
        - "1000:1000"

#
# Profile Database Service
#
  profile-db:
    image: mongo:latest
    restart: always
    ports:
        - "1001:27017"

#
# Match Service
#
  match-service:
    build:
      context: ./match-service/
      dockerfile: Dockerfile
    restart: always
    ports:
        - "2000:2000"

#
# Match Database Service
#
  match-db:
    image: mongo:latest
    restart: always
    ports:
        - "2001:27017" 

#
# Hystrix Monitoring
#
  monitoring:
    build: 
      context: ./monitoring/
      dockerfile: Dockerfile
    restart: always
    ports:
        - "8989:8989" 
        - "8080:8080"

#
# Zipkin Tracing
#
  tracing:
    build: 
      context: ./tracing/
      dockerfile: Dockerfile
    restart: always
    ports:
        - "9411:9411" 
