# ===================================================================
# Common configuration properties
#
# This configuration is common for all services
# ===================================================================

logging:
  level:
    org.springframework.security: INFO
    org.springframework.web: INFO
  file: application.log

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:3000/uaa/users/current



