# ===================================================================
# Auth Service configuration
# ===================================================================

server:
  context-path: /uaa
  port: 3000

spring:
  data:
    mongodb:
      database: test

camel:
  endpoint:
    auth:
      userProfileUri: "rabbitmq:///vento.service.profile/users?connectionFactory=#customConnectionFactory"
      userAuthUri: "rabbitmq:///vento.service.auth/users?connectionFactory=#customConnectionFactory"
---
spring:
  profiles: production
  data:
    mongodb:
      host: auth-db
      database: vento
      port: 27017
