# ===================================================================
# Gateway Service configuration
# ===================================================================

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  prefix: /api
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    profile-service:
        path: /v1/profiles/**
        serviceId: profile-service
        stripPrefix: false
        sensitiveHeaders:

    match-service:
        path: /v1/matches/**
        serviceId: matches-service
        stripPrefix: false
        sensitiveHeaders:

    auth-service:
        path: /v1/uaa/**
        serviceId: auth-service
        stripPrefix: false
        sensitiveHeaders:

server:
  port: 9000
