# ===================================================================
# Match Service configuration
# ===================================================================

server:
  context-path: /matches
  port: 2000

camel:
  connection:
    redis:
      host: localhost
      port: 6379

security:
  oauth2:
    client:
      clientId: match-service
      clientSecret: secret
      grant-type: client_credentials
      scope: server

---
spring:
  profiles: production

camel:
  connection:
    redis:
      host: redis
      port: 6379