# ===================================================================
# Match Service configuration
# ===================================================================

server:
  context-path: /matches
  port: 2000

spring:
  data:
    mongodb:
      database: test

security:
  oauth2:
    client:
      clientId: match-service
      clientSecret: secret
      grant-type: client_credentials
      scope: server

---
spring:
  profiles: production
  data:
    mongodb:
      host: match-db
      database: vento
      port: 27017