# ===================================================================
# Profile Service configuration
# ===================================================================

server:
  context-path: /profiles
  port: 1000

spring:
  data:
    mongodb:
      database: test

security:
  oauth2:
    client:
      clientId: profile-service
      clientSecret: secret
      accessTokenUri: http://localhost:3000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

camel:
  endpoint:
    auth:
      userProfileUri: "rabbitmq:///vento.service.profile/users?connectionFactory=#customConnectionFactory"
      userAuthUri: "rabbitmq:///vento.service.auth/users?connectionFactory=#customConnectionFactory"
---
spring:
  profiles: production
  data:
    mongodb:
      host: profile-db
      database: vento
      port: 27017

security:
  oauth2:
    client:
      accessTokenUri: http://auth-service:3000/uaa/oauth/token
